### ISSUE TITLE
Notebooks 2.0 // Frontend // Setup Basic Spawner App

### ISSUE THREAD

**Issue by ederign** [kubeflow/notebooks#52]

**Comment by Griffin-Sullivan** [comment]
For this issue I will be adding a PR to get the basic app setup and correct directory structure with a proper package.json. I will also include a follow up PR to add cypress to the project for our UI testing.

**Comment by ederign** [comment]
Thanks Griffin! Looking forward to it!

**Comment by Griffin-Sullivan** [comment]
We can close this now with https://github.com/kubeflow/notebooks/pull/73
